/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


public class Library {
    public static void main(String[] args) {
        Restaurant firstRes = new Restaurant("McDonald");
        firstRes.setStars(0); //default stars start from zero
        firstRes.setPrice(4);

        // NOTE if we add 3 review with the same author the function will not edit the rate for thr restaurant
        firstRes.addReview("very good " , "Jason", 3);
        firstRes.addReview("Not bad" , "Heba", 2);
        firstRes.addReview("Amazing" , "Heba", 5);

        System.out.println(firstRes);


        Shop addShop = new Shop("Mecca Mall" , "Mecca Mall is a shopping mall in Amman, Jordan");
        addShop.setStars(3);
        addShop.setPrice(4);
        addShop.addReview("Amazing Shop" , "Heba", 5);
        addShop.addReview("Good" , "Tala", 4);
        addShop.addReview("Bad" , "Mohammed", 2);
        System.out.println(addShop);


        Theater addTheater = new Theater("Rainbow Theater Amman");
        addTheater.setStars(4);
        addTheater.addMovie("Heroes");
        addTheater.addMovie("Vivo");
        addTheater.removeMovie("Vivo");
        addTheater.addMovie("Cinderella story");
        addTheater.addMovieWithReview("Amazing" , "Eman", 5 , "Heroes");
        addTheater.addMovieWithReview("WOW" , "Hala", 5 , "Cinderella story");
        addTheater.addReview("Really nice place" , "Ahmed", 5);
        System.out.println(addTheater);
    }
}