/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


public class Library {
    public static void main(String[] args) {
        Restaurant firstRes = new Restaurant("McDonald");
        firstRes.setStars(0); //default stars start from zero
        firstRes.setPrice(4);

        // NOTE if we add 3 review with the same author the function will not edit the rate for thr restaurant
        firstRes.addReview("very good " , "Jason", 3);
        firstRes.addReview("Not bad" , "Heba", 2);
        firstRes.addReview("Amazing" , "Heba", 5);

        System.out.println(firstRes);
    }
}