/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testRestaurantClass() {
        Restaurant testRestaurant = new Restaurant("KFC");
        testRestaurant.setStars(4);
        testRestaurant.setPrice(5);
        String result = "Name: KFC, Total Rate: 4.0, price category: $$$$$, Review: No review added.";
        assertEquals(result , testRestaurant.toString());
    }

    @Test void testReviewClass() {
        Review testReview = new Review( "Amazing" ,  "Heba",  5);
        String result = "{Author: Heba, body: Amazing, Rate: 5}";
        assertEquals(result , testReview.toString() );
    }


}